/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ApiPaperSessionRouteImport } from './routes/api/paper-session'
import { Route as ApiPaperSessionStartRouteImport } from './routes/api/paper-session.start'
import { Route as ApiPaperSessionStopRouteImport } from './routes/api/paper-session.stop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperSessionRoute = ApiPaperSessionRouteImport.update({
  id: '/api/paper-session',
  path: '/api/paper-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaperSessionStartRoute = ApiPaperSessionStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiPaperSessionRoute,
} as any)
const ApiPaperSessionStopRoute = ApiPaperSessionStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => ApiPaperSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/system': typeof SystemRoute
  '/api/paper-session': typeof ApiPaperSessionRouteWithChildren
  '/api/paper-session/start': typeof ApiPaperSessionStartRoute
  '/api/paper-session/stop': typeof ApiPaperSessionStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/system': typeof SystemRoute
  '/api/paper-session': typeof ApiPaperSessionRouteWithChildren
  '/api/paper-session/start': typeof ApiPaperSessionStartRoute
  '/api/paper-session/stop': typeof ApiPaperSessionStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/paper': typeof PaperRoute
  '/performance': typeof PerformanceRoute
  '/system': typeof SystemRoute
  '/api/paper-session': typeof ApiPaperSessionRouteWithChildren
  '/api/paper-session/start': typeof ApiPaperSessionStartRoute
  '/api/paper-session/stop': typeof ApiPaperSessionStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/paper'
    | '/performance'
    | '/system'
    | '/api/paper-session'
    | '/api/paper-session/start'
    | '/api/paper-session/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/paper'
    | '/performance'
    | '/system'
    | '/api/paper-session'
    | '/api/paper-session/start'
    | '/api/paper-session/stop'
  id:
    | '__root__'
    | '/'
    | '/paper'
    | '/performance'
    | '/system'
    | '/api/paper-session'
    | '/api/paper-session/start'
    | '/api/paper-session/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaperRoute: typeof PaperRoute
  PerformanceRoute: typeof PerformanceRoute
  SystemRoute: typeof SystemRoute
  ApiPaperSessionRoute: typeof ApiPaperSessionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paper-session': {
      id: '/api/paper-session'
      path: '/api/paper-session'
      fullPath: '/api/paper-session'
      preLoaderRoute: typeof ApiPaperSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paper-session/start': {
      id: '/api/paper-session/start'
      path: '/start'
      fullPath: '/api/paper-session/start'
      preLoaderRoute: typeof ApiPaperSessionStartRouteImport
      parentRoute: typeof ApiPaperSessionRoute
    }
    '/api/paper-session/stop': {
      id: '/api/paper-session/stop'
      path: '/stop'
      fullPath: '/api/paper-session/stop'
      preLoaderRoute: typeof ApiPaperSessionStopRouteImport
      parentRoute: typeof ApiPaperSessionRoute
    }
  }
}

interface ApiPaperSessionRouteChildren {
  ApiPaperSessionStartRoute: typeof ApiPaperSessionStartRoute
  ApiPaperSessionStopRoute: typeof ApiPaperSessionStopRoute
}

const ApiPaperSessionRouteChildren: ApiPaperSessionRouteChildren = {
  ApiPaperSessionStartRoute: ApiPaperSessionStartRoute,
  ApiPaperSessionStopRoute: ApiPaperSessionStopRoute,
}

const ApiPaperSessionRouteWithChildren = ApiPaperSessionRoute._addFileChildren(
  ApiPaperSessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaperRoute: PaperRoute,
  PerformanceRoute: PerformanceRoute,
  SystemRoute: SystemRoute,
  ApiPaperSessionRoute: ApiPaperSessionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
